FROM nginx:alpine

LABEL org.opencontainers.image.title="codyssey-custom-nginx"
LABEL org.opencontainers.image.description="Codyssey Docker workstation practice"

COPY site/index.html /usr/share/nginx/html/index.html

EXPOSE 80
